### PR TITLE
fix(snippet): pointers

### PR DESCRIPTION
**Pull request by Climax12**
Added pointer to main-card-card on marketplace, main track List Rows and sort by objects

### CODE REVIEW

**Review by theRealPadster — APPROVED** [review]

**Comment by rxri** [comment]
seriously, with the space?

**Comment by rxri** [comment]
GitHub follows the first pull request title when merging. Get refined github that fixes it or smth @theRealPadster

**Comment by theRealPadster** [comment]
Ah sorry, I never remember. Why does it use the first title and not what's currently there? That's so dumb. Also there is no refined GitHub on my phone.

**Comment by Climax12** [comment]
> Ah sorry, I never remember. Why does it use the first title and not what's currently there? That's so dumb. Also there is no refined GitHub on my phone.

sry i mistakenly place a space :)
I think GitHub follows the Commit title when merging.

**Comment by rxri** [comment]
> Ah sorry, I never remember. Why does it use the first title and not what's currently there? That's so dumb. Also there is no refined GitHub on my phone. 

Idk why it exists but it does

**Pull request merged**
