### PR TITLE
feat(snippets): add "Spinning CD Cover Art"

### PR DESCRIPTION
**Pull request by uboaaaa**
converts the cover art of a currently playing song into a CD shape that spins slowly. for some 2000s nostalgia :^)

### CODE REVIEW

**Comment by theRealPadster** [comment]
There's already a snippet called "Rotating Cover Art", that looks pretty similar, just spins faster. Could you maybe rename this one to better outline the difference between the two?

**Comment by uboaaaa** [comment]
will do, thanks for the heads up. would "CD Style Cover Art" work?

**Comment by theRealPadster** [comment]
Maybe "Spinning CD Cover Art"?

**Comment by uboaaaa** [comment]
that works! i'll make the change now.

**Comment by theRealPadster** [comment]
Oh, can you make the image a JPG as well, just to cut down on the file size? Then I'll merge it in :)

**Review by theRealPadster — APPROVED** [review]

**Pull request merged**
