### PR TITLE
fix: disable homepage recommendations snippet

### PR DESCRIPTION
**Pull request by Climax12**
fixed issue related to #751

### CODE REVIEW

**Comment by somewhat69** [comment]
can you send the css in raw text?

**Comment by Climax12** [comment]
> can you send the css in raw text?
```
[data-testid='home-page'] .contentSpacing > *:not(.view-homeShortcutsGrid-shortcuts, .main-shelf-shelf:has([href="/genre/recently-played"], [href="/section/0JQ5DAnM3wGh0gz1MXnu3z"])) {
  display: none !important;
}
```

**Comment by rxri** [comment]
`:not` is such a performance hitter... I wouldn't really merge this code

**Comment by Climax12** [comment]
> `:not` and `:has` are such a performance hitters... I wouldn't really merge this code

It's used in original one, I just replace .main-home-content with .contentSpacing as it's changed.

**Review by theRealPadster — APPROVED** [review]

**Pull request merged**
