### PR TITLE
feat: improve settings dialog

### PR DESCRIPTION
**Pull request by zhngharry**
Based on #465 

Improves the settings dialog CSS and turn tab order settings into draggable list.
A user can hide a tab when clicking on it, reordering is done via drag and drop

Before:
image

After:
image

### CODE REVIEW

**Comment by CharlieS1103** [comment]
The entire marketplace is being overhauled, might be able to apply these changes when it's made public though

**Comment by rxri** [comment]
> The entire marketplace is being overhauled, might be able to apply these changes when it's made public though

He's aware of v3.

**Comment by zhngharry** [comment]
> The entire marketplace is being overhauled, might be able to apply these changes when it's made public though

Yeah I know, but i'd already implemented most of it so i figured i'd just open the PR

I can recreate it in v3 if wanted

**Comment by CharlieS1103** [comment]
@zhngharry In that case I'd be down to merge as long as @theRealPadster is as well, up to everyone else if they want a new release for it and such though.

**Comment by theRealPadster** [comment]
I'm down to merge it, I don't see any harm in some final QOL updates before v3

**Comment by theRealPadster** [comment]
Could we add some text to explain that you can click to disable them? It's not obvious. Maybe something like "drag and drop to reorder, click to toggle on and off"

**Comment by zhngharry** [comment]
Looks like this now

image

**Review by theRealPadster — APPROVED** [review]
Love it, thanks!

**Pull request merged**
